version: '3.7'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" 
    networks:
      - my_network

  fastapi:
    build: .  # Path to your FastAPI app Dockerfile
    ports:
      - "8000:8000"  # Adjust port if needed
    depends_on:
      - qdrant
    networks:
      - my_network

networks:
  my_network:
    driver: bridge